// District AI — native Android client.
//
// ⛔ THIS BUILD IS SELF-CONTAINED. The API contract fixtures under contracts/ are
// generated by the server's own test suite and committed here; tests read them and
// nothing compiles them.

pluginManagement {
    // Convention plugins live in an included build so they compile against the
    // same version catalog the app uses. See build-logic/.
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // ⛔ FAIL_ON_PROJECT_REPOS is deliberate. A module declaring its own
    // repositories{} block would resolve dependencies from a source this file
    // does not list, which is exactly how a supply-chain surprise gets in
    // without a diff anyone reviews. Keep repository declarations here only.
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // ⛔ JITPACK IS MODULE-FILTERED, AND THE FILTER IS THE POINT. JitPack builds
        // arbitrary GitHub repositories on demand, so an unfiltered entry would let ANY
        // dependency in the graph resolve from it — the exact supply-chain surprise the
        // FAIL_ON_PROJECT_REPOS note above exists to prevent. exclusiveContent admits
        // exactly one artifact: the audioswitch fork that io.livekit:livekit-android
        // (itself on Maven Central) pins BY COMMIT HASH in its own version catalog —
        // com.github.davidliu:audioswitch is published nowhere else. Adding anything
        // further to this filter is a supply-chain decision, not a convenience.
        exclusiveContent {
            forRepository {
                maven { url = uri("https://jitpack.io") }
            }
            filter {
                includeModule("com.github.davidliu", "audioswitch")
            }
        }
    }
}

rootProject.name = "district-android"

// Gradle's configuration cache and type-safe project accessors.
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")

// ── core ─────────────────────────────────────────────────────────────────────
// DTOs mirroring the District AI API responses, plus the contract test that pins them
// against fixtures generated from the real route handlers.
//
// The fixtures in contracts/ are GENERATED by the server's contract test, never hand-edited.
// A fixture change is committed together with the DTO change it implies. Rationale and the
// two-sided failure mechanism are documented in ContractFixtureTest.kt.
include(":core:core-model")

// Token storage and the refresh coordinator. The interesting logic here is not the
// encryption — it is obeying the server's mandatory refresh-token rotation without ever
// presenting the same token twice, because a replay revokes the whole token family and
// signs the user out. See TokenRefreshCoordinator.
include(":core:core-auth")
// The authenticated HTTP client, and the translation of this API's THREE different error
// envelopes into one result type the UI can branch on. Deliberately plain OkHttp +
// kotlinx.serialization rather than Retrofit — see the note in its build file.
include(":core:core-network")
// Repositories over core-network. Holds the app's active-workspace selection, which on
// native is explicit state rather than the web's httpOnly cookie.
include(":core:core-data")

// Colour, type, shape, motion and the primitive composables: the port of the web
// dashboard's primitive component library and its design-token set.
//
// ⛔ It depends on NO other project module, deliberately. It is the bottom of the UI stack, and
// the moment a primitive takes a DTO it stops being reusable and becomes a screen.
//
// ⚠️ Adding a module here is only half the job — it must also be added to the `kover { }`
// dependency list in build.gradle.kts, or it is SILENTLY excluded from the coverage measurement
// rather than being a build error.
include(":core:core-designsystem")

// The LiveKit wrapper: one module boundary, one ProGuard surface, one lockfile for
// the entire media stack. UI and Telecom stay in :app; this module owns the
// CallEngine seam so every consumer tests against an interface, not the SDK.
// ⛔ Adding a module here requires the kover() entry in build.gradle.kts too —
// a module missing there is silently excluded from coverage, not a build error.
include(":core:core-media")
