package com.distronode.districtai

import io.sentry.SentryOptions
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The Sentry configuration, asserted without initialising Sentry.
 *
 * ⛔ THIS TESTS THE ONLY PART THAT CAN BE SILENTLY WRONG. Every setting here has a failure mode
 * that produces a GREEN build and a working app: PII quietly re-enabled sends customer data to a
 * vendor, a non-null `tracesSampleRate` spends ingest budget, a hardcoded environment files debug
 * crashes as production. None of those breaks anything a compiler or a device can notice, which is
 * precisely why they are pinned here.
 *
 * ⚠️ NO ROBOLECTRIC AND NO `SentryAndroid.init`. `apply` is typed on [SentryOptions] so a plain
 * JVM object is enough — see the ⚠️ on that function for why it is not typed on
 * `SentryAndroidOptions`. Calling the real `init` would install a process-wide uncaught-exception
 * handler and an ANR watchdog into the test JVM, which nothing can then remove.
 */
class DistrictSentryTest {

    private fun optionsFor(
        dsn: String = "https://key@o1.ingest.de.sentry.io/2",
        environment: String = "release",
    ): SentryOptions = SentryOptions().also { DistrictSentry.apply(it, dsn, environment) }

    @Test
    fun `the dsn and environment are taken from the caller`() {
        val options = optionsFor(dsn = "https://abc@o9.ingest.de.sentry.io/7", environment = "debug")

        assertEquals("https://abc@o9.ingest.de.sentry.io/7", options.dsn)
        assertEquals("debug", options.environment)
    }

    @Test
    fun `personally identifiable information is never sent by default`() {
        // ⛔ THE ONE ASSERTION THAT IS ABOUT A PROMISE RATHER THAN A PREFERENCE. `sendDefaultPii`
        // attaches the device user and the request IP; this app's payloads are other people's
        // call transcripts and contact records under a residency claim that is published.
        assertFalse(optionsFor().isSendDefaultPii)
    }

    @Test
    fun `tracing and profiling are disabled rather than sampled at zero`() {
        val options = optionsFor()

        // ⛔ NULL, NOT 0.0. A rate of 0.0 leaves the tracing machinery armed and lets a manually
        // started transaction through; null is what makes the spend impossible. Asserted with
        // assertNull specifically so a future `= 0.0` "no-op" change fails here.
        assertNull(options.tracesSampleRate)
        assertNull(options.profilesSampleRate)
    }

    @Test
    fun `an environment string is carried verbatim, including an unexpected one`() {
        // ⚠️ BUILD_TYPE is generated by AGP, so today it is exactly "debug" or "release" — but a
        // future build type (a "staging" variant, a Play internal-track flavour) must land in
        // Sentry under its own name rather than be normalised into one of the two this code
        // happens to know about. Nothing here inspects the value, and that is deliberate.
        assertEquals("staging", optionsFor(environment = "staging").environment)
    }

    @Test
    fun `the built-in dsn is exactly the one the build was configured with`() {
        // ⛔ THE DSN IS NO LONGER A COMMITTED LITERAL, SO WHAT CAN GO WRONG IS THE PLUMBING. It
        // travels from `-PdistrictSentryDsn` / `DISTRICT_SENTRY_DSN` through a string template
        // into a generated Java field; a quoting or trimming mistake there would ship a DSN that
        // differs from the one supplied, or an empty one, with every build green.
        // app/build.gradle.kts hands the value it resolved to this test as a system property, so
        // the two ends are compared directly. With nothing configured both are empty, which is
        // the default and means "Sentry disabled" (see DistrictSentryGuardTest).
        val configured = System.getProperty("district.sentry.dsn")
        assertNotNull(
            "System property district.sentry.dsn is not set. It is configured on this module's " +
                "test tasks in app/build.gradle.kts; without it this test compares nothing.",
            configured,
        )
        assertEquals(configured, BuildConfig.SENTRY_DSN)
    }

    @Test
    fun `the built-in dsn is either empty or a well-formed ingest url`() {
        // ⚠️ EMPTY IS THE DEFAULT AND IS VALID: it means the build reports nothing. Anything else
        // must at least have the shape of a DSN (https, a public key, a host, a numeric project
        // id), so a value pasted into the wrong property (an org slug, an auth token, a URL
        // without its key) fails here rather than silently reporting nowhere from a device.
        val dsn = BuildConfig.SENTRY_DSN
        assertTrue(
            "SENTRY_DSN must be empty or https://<key>@<host>/<project id>, got '$dsn'",
            dsn.isEmpty() || DSN_SHAPE.matches(dsn),
        )
    }

    private companion object {
        val DSN_SHAPE = Regex("^https://[^@/\\s]+@[^/\\s]+(/[^\\s]*)?/[0-9]+$")
    }
}
