package com.distronode.districtai.core.model

import java.io.File
import kotlinx.serialization.json.Json
import org.junit.Assert.assertTrue

/**
 * Where the committed fixtures are, and how to read one.
 *
 * ⛔ EXTRACTED SO A SECOND CONTRACT TEST CLASS CAN EXIST AT ALL. `ContractFixtureTest` reached
 * detekt's LargeClass ceiling as endpoints were added, and the only healthy answer to that is more
 * classes rather than a raised threshold — but each of them needs the same directory lookup and
 * the same strict decoder, and two copies would be two chances for one of them to drift lenient.
 *
 * ⛔ `ignoreUnknownKeys = false` IS THE WHOLE MECHANISM, AND IT LIVES HERE NOW. With the default
 * `true`, a field added server-side would be silently dropped and every contract test would keep
 * passing while the app quietly ignored data it was supposed to show. Do not relax it to make a
 * failure go away — the failure IS the signal, and the fix is to add the field to the DTO.
 */
internal object ContractFixtures {

    /**
     * ⛔ See [dir]: this decoder is strict on purpose and is shared so it cannot be strict in one
     * test class and lenient in another.
     *
     * ⚠️ `explicitNulls = false` because the fixtures are real server output, which omits keys
     * rather than sending explicit nulls in places; DTO defaults cover those.
     */
    val json: Json = Json {
        ignoreUnknownKeys = false
        explicitNulls = false
    }

    /**
     * ⚠️ Supplied as a system property by `core/core-model/build.gradle.kts`. Without it a test
     * cannot find the fixtures and would otherwise pass by verifying nothing, so its absence is
     * asserted rather than defaulted.
     */
    val dir: File by lazy {
        val configured = System.getProperty("district.contracts.dir")
        assertTrue(
            "System property district.contracts.dir is not set. It is configured in " +
                "core/core-model/build.gradle.kts; without it this test cannot find the " +
                "fixtures and would otherwise pass by verifying nothing.",
            !configured.isNullOrBlank(),
        )
        File(configured!!)
    }

    fun read(name: String): String {
        val file = File(dir, name)
        assertTrue(
            "Missing contract fixture ${file.absolutePath}. Fixtures are generated by the " +
                "server's contract test suite (CONTRACTS_UPDATE=1); regenerate them there.",
            file.isFile,
        )
        return file.readText()
    }
}
