package com.distronode.districtai.core.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.InvalidKeyException
import java.security.KeyStore
import java.security.UnrecoverableEntryException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-GCM over a key held in the Android Keystore, for [KeystoreTokenStore]'s values.
 *
 * ⛔ THIS IS NOT HAND-ROLLED CRYPTOGRAPHY. The key never leaves the Keystore (hardware-backed
 * where the device provides it), the cipher is the platform's AES/GCM/NoPadding, and the IV is
 * generated by the provider rather than by this code — see [encrypt]. Those are the three things
 * that go wrong when people do roll their own.
 *
 * ⛔ FAIL CLOSED, ALWAYS. Every path returns null on ANY failure rather than throwing. A key
 * invalidated by a device-security change, a Keystore that will not load, a value written by an
 * older scheme — all of them mean "there is no usable value here", whose correct outcome upstream
 * is a clean re-login. Throwing would crash on launch instead, and returning a partially-decoded
 * value would be worse still.
 *
 * ⚠️ EXTRACTED FROM [KeystoreTokenStore] RATHER THAN INLINED THERE, and the reason is worth
 * recording so it is not folded back: the store gained a third slot (the revoke outbox) and
 * crossed detekt's 11-function class ceiling. Splitting on the seam between "what is stored" and
 * "how it is encrypted" is the cut that leaves both halves readable — the alternative was raising
 * a threshold to accommodate a class that had genuinely grown two responsibilities.
 */
internal class KeystoreCipher {

    /** Encrypt one value; [encryptAll] holds the rules. */
    fun encrypt(plaintext: String): String? = encryptAll(plaintext)?.single()

    /**
     * Encrypt every value under the same key, or return null if any of them cannot be.
     *
     * ⛔ A KEY THAT IS PRESENT BUT UNUSABLE IS REPLACED, ONCE. A device-security change (a new
     * lock screen, removed biometrics) can leave the key under [KEY_ALIAS] in place while the
     * Keystore refuses it: `Cipher.init` throws `KeyPermanentlyInvalidatedException` or another
     * [InvalidKeyException], or the lookup itself throws `UnrecoverableKeyException` (an
     * [UnrecoverableEntryException]). Lookup only generates a key when the alias is EMPTY, so
     * without this every later write would fail and no sign-in could be stored again. On either
     * of those, the alias is deleted and every value is encrypted again, which generates a fresh
     * key. Nothing readable is lost: whatever the old key protected cannot be decrypted anyway,
     * and that includes a revoke outbox entry [KeystoreTokenStore] keeps across a wipe.
     *
     * ⛔ NEVER A SECOND TIME. If the fresh key fails as well, this returns null and the caller
     * fails closed exactly as before. Any other failure (a Keystore that will not load or answer,
     * an IV of the wrong length) is not the key's fault, so it fails closed without touching
     * the key.
     *
     * ⚠️ ALL VALUES ARE RE-ENCRYPTED AFTER A REPLACEMENT, not only the one that failed: a value
     * already encrypted under the deleted key would never decrypt again.
     */
    fun encryptAll(vararg plaintexts: String): List<String>? =
        runCatching { plaintexts.map(::encryptOne) }
            .recoverCatching { failure ->
                if (failure !is InvalidKeyException && failure !is UnrecoverableEntryException) throw failure
                loadKeyStore().deleteEntry(KEY_ALIAS)
                plaintexts.map(::encryptOne)
            }
            .getOrNull()

    /**
     * Encrypt to `base64(iv || ciphertext)`, throwing on any failure.
     *
     * ⛔ THE IV IS THE PROVIDER'S, NOT OURS. `Cipher.init` in ENCRYPT_MODE against an
     * AndroidKeyStore key generates a fresh random IV, which is then read back off the cipher.
     * Supplying our own would invite the one catastrophic GCM mistake: reusing an IV under the
     * same key destroys both confidentiality and authenticity. The Keystore additionally refuses
     * a caller-supplied IV for this reason (setRandomizedEncryptionRequired defaults to true).
     */
    private fun encryptOne(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv
        require(iv.size == IV_LENGTH) { "unexpected GCM IV length ${iv.size}" }
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(iv + ciphertext, Base64.NO_WRAP)
    }

    /**
     * ⚠️ TAKES A NULLABLE STORED VALUE so callers do not each need an absence check. An absent
     * key and an undecryptable one are the same answer here — there is no usable value — and
     * making the caller distinguish them would invite one of them to be handled and the other
     * forgotten.
     */
    fun decrypt(stored: String?): String? = runCatching {
        val value = stored ?: return null
        val bytes = Base64.decode(value, Base64.NO_WRAP)
        if (bytes.size <= IV_LENGTH) return null
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_LENGTH_BITS, bytes, 0, IV_LENGTH),
        )
        String(cipher.doFinal(bytes, IV_LENGTH, bytes.size - IV_LENGTH), Charsets.UTF_8)
    }.getOrNull()

    /**
     * The Keystore key, created on first use.
     *
     * ⚠️ No `setUserAuthenticationRequired(true)`. Requiring a device unlock to read the token
     * would break every background refresh, the FCM-triggered work and the Telecom call
     * handling, all of which run with the screen locked. The token is protected
     * by the app sandbox plus Keystore extraction resistance, which is the same posture
     * EncryptedSharedPreferences gave.
     */
    private fun secretKey(): SecretKey {
        (loadKeyStore().getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                // GCM is an AEAD mode and takes no padding; setting one is rejected.
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    private fun loadKeyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    private companion object {
        /**
         * ⚠️ Renaming this orphans every existing install's credential — the values already on
         * disk become permanently undecryptable, so every user silently lands on the login
         * screen. Migrate rather than rename.
         */
        const val KEY_ALIAS = "district_native_session_key_v1"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_LENGTH = 12
        const val TAG_LENGTH_BITS = 128
        const val KEY_SIZE_BITS = 256
    }
}
