package com.distronode.districtai.core.auth

import java.security.MessageDigest
import java.security.SecureRandom
import java.util.Base64

/**
 * PKCE (RFC 7636) for the native login handshake.
 *
 * ⛔ PKCE IS LOAD-BEARING HERE, NOT CEREMONY. The authorization code comes back over the
 * `districtai://auth` custom scheme, and on Android ANY app can register the same scheme.
 * A malicious app that did so would receive our callback and hold a real code. PKCE is what
 * makes that code worthless to it: the challenge is sent up front, the verifier is never
 * observable, and the exchange requires the verifier. The server's own native-oauth.ts says
 * the same thing about iOS.
 *
 * ⛔ THE CHALLENGE IS THE DIGEST OF THE VERIFIER *STRING*, NOT OF DECODED BYTES. RFC 7636
 * defines `code_challenge = base64url(SHA256(ASCII(code_verifier)))`, and the server
 * implements exactly that. Hashing anything else produces a value that is well-formed but
 * always wrong, which presents as "PKCE always fails" with nothing to point at — the server
 * file flags this specific trap. [PkceVectorTest] pins this against vectors generated by the
 * server's own implementation so the two can never drift silently.
 *
 * ⛔ BASE64URL WITHOUT PADDING. `Base64.getUrlEncoder().withoutPadding()`. Leaving the `=`
 * padding on yields a 44-character challenge, which fails the server's
 * `isValidCodeChallenge` (`^[A-Za-z0-9\-_]{43}$`) at authorize time.
 */
object Pkce {

    /**
     * Bytes of entropy in a verifier.
     *
     * 32 bytes base64url-encodes to 43 characters, which is RFC 7636's MINIMUM verifier
     * length and the server's `isValidCodeVerifier` floor (43..128). Chosen at the minimum
     * deliberately: it is 256 bits of entropy, and a longer verifier buys nothing while
     * moving closer to the 128-character ceiling.
     */
    private const val VERIFIER_BYTES = 32

    /**
     * Bytes of entropy in the `state` parameter.
     *
     * ⚠️ `state` is NOT part of PKCE and does a different job: it binds the callback to the
     * request this app started, so a code injected by another app or an old callback replayed
     * from history is rejected before it is ever exchanged.
     */
    private const val STATE_BYTES = 32

    private val random = SecureRandom()

    /** base64url, unpadded, as RFC 7636 specifies. */
    private val encoder: Base64.Encoder = Base64.getUrlEncoder().withoutPadding()

    /** A fresh verifier + its S256 challenge + a state value, for one login attempt. */
    fun newChallenge(): PkceChallenge {
        val verifier = randomBase64Url(VERIFIER_BYTES)
        return PkceChallenge(
            verifier = verifier,
            challenge = deriveChallenge(verifier),
            state = randomBase64Url(STATE_BYTES),
        )
    }

    /**
     * `base64url(SHA-256(ASCII(verifier)))`.
     *
     * Exposed so [PkceVectorTest] can assert it against the server's output for the same
     * inputs rather than only testing round-trip self-consistency, which would agree with
     * itself while both sides were wrong.
     */
    fun deriveChallenge(verifier: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
            // US-ASCII, matching RFC 7636's ASCII(). The verifier alphabet is
            // [A-Za-z0-9-._~] so this is equivalent to UTF-8 here, but it is spelled out
            // because the equivalence is a property of the alphabet, not of the code.
            .digest(verifier.toByteArray(Charsets.US_ASCII))
        return encoder.encodeToString(digest)
    }

    private fun randomBase64Url(bytes: Int): String {
        val buffer = ByteArray(bytes)
        random.nextBytes(buffer)
        return encoder.encodeToString(buffer)
    }
}

/**
 * One login attempt's secrets.
 *
 * ⚠️ [verifier] must survive the trip out to the system browser and back, but must NEVER
 * leave the device. It is held in memory by the login flow, not persisted: a login attempt
 * that does not complete before the process dies is simply restarted, which costs the user a
 * tap and avoids writing a live credential-exchange secret to disk.
 */
data class PkceChallenge(
    val verifier: String,
    val challenge: String,
    val state: String,
)
