plugins {
    id("district.android.library")
    alias(libs.plugins.kotlin.serialization)
}

android {
    // ⚠️ AGP 9 flipped android.uniquePackageNames to true, so every library module needs
    // its own distinct namespace. Reusing the app's would fail the build.
    namespace = "com.distronode.districtai.core.model"
}

dependencies {
    api(libs.kotlinx.serialization.json)

    testImplementation(libs.junit)
}

// ── Contract fixtures ────────────────────────────────────────────────────────
// The fixtures are generated by the server's test suite from the real route
// handlers and committed under contracts/ at the root of this project.
//
// ⛔ The path is passed as a system property rather than resolved with a relative
// path inside the test. A Gradle test's working directory is the MODULE directory,
// so `../../contracts` happens to work today and would break the moment this module
// moves — silently, because a missing directory reads as "no fixtures" and the
// assertion below is what turns that into a failure rather than a pass.
tasks.withType<Test>().configureEach {
    val contractsDir = rootProject.file("contracts")

    systemProperty("district.contracts.dir", contractsDir.absolutePath)

    // ⛔ DECLARING THE FIXTURES AS AN INPUT IS NOT OPTIONAL, AND OMITTING IT MAKES THIS
    // GATE USELESS. Gradle only re-runs a task when one of its declared inputs changes.
    // The fixtures reach the test through a system property, which Gradle cannot see
    // into, so without this the task stays UP-TO-DATE across a fixture change and the
    // contract is never re-checked.
    //
    // Measured, not theorised: editing district-calls.json to add an unmodelled field
    // produced "BUILD SUCCESSFUL in 1s" with the test never running. A gate that does not
    // re-run when its input changes is worse than no gate, because it reports success.
    inputs.dir(contractsDir)
        .withPropertyName("androidContractFixtures")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}

// ── The contract manifest (ContractManifestTest) ─────────────────────────────
// ContractManifestTest answers "which fixtures does a Kotlin test actually decode?" by scanning
// the Kotlin TEST SOURCES of every module for quoted `*.json` literals. It needs two things from
// here: where the tree is, and a declaration that the tree is an input.
//
// ⛔ EVERY MODULE, NOT JUST THIS ONE. Eleven of the 152 fixtures are decoded by :core:core-auth
// and :core:core-network, which run in their own test JVMs. A root-relative walk is the only way
// one test can see all of them; that is also why the manifest cannot be built from a runtime
// registry inside this module's ContractFixtures. The reasoning is written out in full in
// ContractManifestTest's class doc.
//
// ⛔ `inputs.files` IS AS LOAD-BEARING HERE AS IT IS ABOVE, FOR THE SAME MEASURED REASON. The
// sources reach the test through a system property, which Gradle cannot see into, so without the
// declaration this task stays UP-TO-DATE when another module's test drops or adds a fixture
// reference and the manifest is never re-checked. `files` rather than `dir` deliberately: a
// pattern-filtered tree keeps `build/` and `.gradle*/` out of the fingerprint, which a whole-root
// `inputs.dir` could not.
tasks.withType<Test>().configureEach {
    val androidRoot = rootProject.projectDir

    systemProperty("district.android.root", androidRoot.absolutePath)

    val kotlinTestSources = rootProject.fileTree(androidRoot) {
        include("**/src/test*/**/*.kt")
        exclude("**/build/**", "**/.gradle/**", "**/.gradle-home/**", "**/.git/**")
    }

    inputs.files(kotlinTestSources)
        .withPropertyName("kotlinTestSources")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}
