package com.distronode.districtai.core.network

import com.distronode.districtai.core.model.CODE_OVERAGE_CAP_REACHED
import com.distronode.districtai.core.model.CODE_SUBSCRIPTION_INACTIVE
import com.distronode.districtai.core.model.MemberAddRequest
import com.distronode.districtai.core.model.MemberRoleRequest
import java.io.File
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import mockwebserver3.MockResponse
import mockwebserver3.MockWebServer
import okhttp3.Headers
import okhttp3.OkHttpClient
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the ERROR envelope against a fixture generated from the real route handler.
 *
 * ⛔ WHY AN ERROR SHAPE GETS THE FIXTURE TREATMENT AT ALL. Most do not — an error carries a
 * sentence to show and a code to branch on, so a missed field costs a vaguer message. This one
 * is different: `code: "REGIONS_DEGRADED"` is what stops the app rendering "you have no
 * workspaces" when the truth is "one region did not answer". That conflation can send a paying
 * customer to a checkout page on the web. If the server ever renames the
 * code, the client silently falls back to a generic failure and the specific, correct message
 * is lost — so it is worth a committed sample.
 *
 * ⛔ AND IT LIVES HERE, NOT IN core-model's ContractFixtureTest, because [ApiErrorEnvelope]
 * lives here, next to the mapping that consumes it. Pinning a test-only copy of the shape in
 * core-model would prove a duplicate correct while the shipping type drifted.
 */
class ApiErrorEnvelopeContractTest {

    /**
     * ⛔ STRICT, UNLIKE THE SHIPPED PARSER, AND THAT ASYMMETRY IS THE WHOLE MECHANISM.
     * [DistrictApiClient.DEFAULT_JSON] sets `ignoreUnknownKeys = true` so a field added
     * server-side degrades to "ignored" on already-installed builds instead of breaking every
     * response. Here it is false, so the same addition reds CI and gets a decision made about
     * it. Strict in the gate, lenient in the field.
     */
    private val strictJson = Json {
        ignoreUnknownKeys = false
        explicitNulls = false
    }

    private fun fixture(name: String): String {
        val configured = System.getProperty("district.contracts.dir")
        assertTrue(
            "System property district.contracts.dir is not set. It is configured in " +
                "core/core-network/build.gradle.kts; without it this test cannot find the " +
                "fixture and would otherwise pass by verifying nothing.",
            !configured.isNullOrBlank(),
        )
        val file = File(configured!!, name)
        assertTrue(
            "Missing contract fixture ${file.absolutePath}. Fixtures are generated by the " +
                "server's contract test suite (CONTRACTS_UPDATE=1); regenerate them there.",
            file.isFile,
        )
        return file.readText()
    }

    @Test
    fun `the degraded-regions envelope decodes and names the failed regions`() {
        val raw = fixture("district-workspace-list-degraded.json")

        val envelope = strictJson.decodeFromString(ApiErrorEnvelope.serializer(), raw)

        assertEquals(ApiErrorEnvelope.CODE_REGIONS_DEGRADED, envelope.code)
        assertTrue("must name which regions failed", envelope.degradedRegions.isNotEmpty())
        assertTrue("must carry a message worth showing", !envelope.error.isNullOrBlank())

        // ⛔ NO `success` KEY AT ALL. This is the shape that would make a strict
        // {success, error} DTO throw — which it would also do on every 401, 403 and 404 in the
        // API, since the shared auth guard answers the same way. That is why the shipped error
        // parser treats every field as optional.
        assertNull("this envelope carries no success key", envelope.success)
        assertFalse(raw.contains("\"success\""))
    }

    /**
     * ⛔ THE SECOND ERROR SHAPE, AND THE SECOND ERROR BODY IN THIS API WORTH A COMMITTED SAMPLE.
     * The bar for pinning an error is that the BODY is the product rather than a sentence a
     * client could replace and lose nothing. The degraded envelope above clears it because its
     * `code` decides whether "we could not look" is drawn as "there is nothing". This one clears
     * it because its `error` is the only thing that tells an operator where the switch is: the
     * enrichment opt-in lives on the workspace, and the message names the exact settings page.
     * Replace it with "you do not have permission" and the operator is left with a button that
     * fails, looking at their own account for a control that is not there.
     *
     * ⛔ AND IT IS THE `{success:false, error}` ENVELOPE — a ROUTE's own, not the shared auth
     * guard's bare `{error}` that the degraded fixture pins. Three envelopes exist and this type
     * normalises all of them; having a real sample of a second one is what keeps that
     * normalisation tested against server output rather than against shapes someone typed out.
     *
     * ⚠️ IT LIVES HERE RATHER THAN IN core-model's ContractFixtureTest FOR THE SAME REASON THE
     * DEGRADED ONE DOES: [ApiErrorEnvelope] lives in this module, next to the mapping that
     * consumes it, and core-model has no type that decodes an error body at all. Pinning it over
     * there would mean inventing a test-only copy of the shape and proving the copy correct while
     * the shipping type drifted.
     */
    @Test
    fun `the enrichment opt-in refusal decodes, and names the setting that turns it on`() {
        val raw = fixture("district-enrich-disabled.json")

        val envelope = strictJson.decodeFromString(ApiErrorEnvelope.serializer(), raw)

        // ⚠️ PRESENT AND FALSE, unlike the degraded body where the key is absent entirely. That
        // contrast is the whole reason `success` is a nullable Boolean rather than a Boolean with
        // a default: absent and false are different facts about which layer refused.
        assertEquals(false, envelope.success)
        assertTrue("must carry a message worth showing", !envelope.error.isNullOrBlank())
        assertTrue(
            "the message must name where the opt-in lives, or it is not worth pinning",
            envelope.error!!.contains("Skills & Integrations"),
        )

        // A route's own refusal has nothing machine-readable to branch on, so the client has no
        // choice but to show the sentence. Asserted so a future `code` is a decision rather than
        // a surprise.
        assertNull("a route's own refusal carries no code", envelope.code)
        assertTrue(envelope.degradedRegions.isEmpty())
    }

    @Test
    fun `the shipped lenient parser reads the opt-in refusal the same way`() {
        // ⚠️ THE HALF THAT MATTERS IN THE FIELD. The strict decode above proves the fields are
        // there; this proves the parser the app actually ships still reaches the message. They
        // are different `Json` instances by design — strict in the gate, lenient in the field —
        // and only this one is what a user sees.
        val envelope = DistrictApiClient.DEFAULT_JSON.decodeFromString(
            ApiErrorEnvelope.serializer(),
            fixture("district-enrich-disabled.json"),
        )

        assertEquals(false, envelope.success)
        assertTrue(envelope.error!!.contains("Skills & Integrations"))
    }

    /**
     * ⛔ THE THIRD AND FOURTH ERROR BODIES WORTH A COMMITTED SAMPLE, AND THEY CLEAR THE BAR FOR A
     * DIFFERENT REASON THAN THE TWO ABOVE. The degraded envelope is pinned because its `code`
     * decides whether "we could not look" is drawn as "there is nothing"; the enrichment refusal
     * because its `error` names the setting. These two are pinned because the CLIENT'S ENTIRE
     * OUTCOME MAPPING HANGS OFF THE CODE: `MembersRepository` turns `member_exists` into
     * "Already a member" and `last_agency_member` into "Every workspace needs at least one agency
     * member", and anything it does not recognise falls back to the server's operator-facing
     * sentence. A rename of either code would leave the app compiling, the requests succeeding in
     * their refusal, and the two specific messages silently gone.
     *
     * ⛔ AND THEY MUST NOT COLLIDE. The two refusals mean opposite things — one is a mistake the
     * operator can fix by choosing a different address, the other is not a mistake at all — so the
     * codes being DISTINCT is as load-bearing as either value.
     */
    @Test
    fun `both membership refusals decode, carry distinct codes, and are the routes own envelope`() {
        val duplicate = fixture("district-member-duplicate.json")
        val lastAgency = fixture("district-member-last-agency.json")

        val duplicateEnvelope = strictJson.decodeFromString(ApiErrorEnvelope.serializer(), duplicate)
        val lastAgencyEnvelope =
            strictJson.decodeFromString(ApiErrorEnvelope.serializer(), lastAgency)

        assertEquals("member_exists", duplicateEnvelope.code)
        assertEquals("last_agency_member", lastAgencyEnvelope.code)
        assertTrue(
            "the two refusals mean opposite things and must never share a code",
            duplicateEnvelope.code != lastAgencyEnvelope.code,
        )

        // ⚠️ PRESENT AND FALSE, like the enrichment refusal and unlike the degraded body where the
        // key is absent entirely. These are a ROUTE's own 409s, not the shared auth guard's bare
        // `{error}` — a third shape this one type has to normalise.
        assertEquals(false, duplicateEnvelope.success)
        assertEquals(false, lastAgencyEnvelope.success)
        assertTrue(!duplicateEnvelope.error.isNullOrBlank())
        assertTrue(!lastAgencyEnvelope.error.isNullOrBlank())
        assertTrue(duplicateEnvelope.degradedRegions.isEmpty())
    }

    /**
     * ⛔ THE HALF THAT ACTUALLY MATTERS, AND IT IS RUN OVER A REAL SOCKET. Decoding the envelope
     * proves the fields are in the file; this proves the code SURVIVES `mapFailure` — which is
     * where it could be lost, because that function has four earlier branches keyed on the status
     * alone and a 409 has to fall all the way through to `HttpFailure` for the code to be carried
     * at all. A client that reached `Forbidden` or a bare `HttpFailure(code = null)` here would
     * show the generic failure and nothing in a decode test would notice.
     *
     * ⚠️ MockWebServer rather than a stub, for the reason this module's client test states: what is
     * under test is the real body read and the real status mapping.
     */
    @Test
    fun `a 409 carrying either fixture reaches the caller as HttpFailure with the code intact`() =
        runTest {
            val server = MockWebServer()
            server.start()
            try {
                val api = HttpMembersApi(
                    DistrictApiClient(
                        baseUrl = server.url("/"),
                        httpClient = OkHttpClient(),
                        tokens = signedInCoordinator(FakeRefreshApi().apply { rotating() }),
                    ),
                )

                server.enqueue(
                    MockResponse(
                        code = 409,
                        headers = Headers.headersOf("Content-Type", "application/json"),
                        body = fixture("district-member-duplicate.json"),
                    ),
                )
                val add = api.addMember(
                    MemberAddRequest(workspaceId = "ws-1", email = "a@example.com", role = "client"),
                )

                server.enqueue(
                    MockResponse(
                        code = 409,
                        headers = Headers.headersOf("Content-Type", "application/json"),
                        body = fixture("district-member-last-agency.json"),
                    ),
                )
                val demote = api.changeMemberRole(
                    MemberRoleRequest(workspaceId = "ws-1", email = "a@example.com", role = "viewer"),
                )

                assertEquals(
                    ApiResult.HttpFailure::class,
                    (add as ApiResult.Failure)::class,
                )
                assertEquals("member_exists", (add as ApiResult.HttpFailure).code)
                assertEquals(HTTP_CONFLICT, add.status)
                assertEquals("last_agency_member", (demote as ApiResult.HttpFailure).code)
                assertEquals(HTTP_CONFLICT, demote.status)

                // ⛔ THE SERVER'S SENTENCE IS STILL CARRIED. The client prefers its own copy for
                // these two, but anything that stopped delivering the message would also break
                // every OTHER 4xx, where the server's wording is the only specific thing there is.
                assertTrue(add.message.contains("already a member"))
            } finally {
                server.close()
            }
        }

    /**
     * ⛔ THE FIFTH AND SIXTH ERROR BODIES WORTH A COMMITTED SAMPLE, AND THE PAIR IS PINNED TOGETHER
     * BECAUSE WHAT MATTERS IS THAT THEY ARE DIFFERENT. Both refuse the same action — placing an
     * outbound call — and both are refusals of the whole workspace rather than of this number, but
     * they mean opposite things about the account and have opposite remedies: `subscription_inactive`
     * is an unpaid plan, fixed on the web; `overage_cap_reached` is a workspace in GOOD standing
     * that chose a hard cap and used its included minutes, fixed by changing the policy. Wording
     * the second as a payment problem sends an operator to check a card that is working.
     *
     * ⛔ AND THE CODE IS THE ONLY THING THAT SEPARATES THEM AT THE CLIENT. `DialRepository` branches
     * on it and falls back to the server's operator-facing sentence for anything else, so a rename
     * would leave the app compiling, the refusals still refusing, and both specific messages
     * silently gone — the same failure the two membership codes above are pinned against.
     *
     * ⚠️ ONLY THE SUBSCRIPTION BODY HAS A COMMITTED FIXTURE. `overage_cap_reached` is emitted by
     * the same shared guard module on a 409, and no route in the contract suite reaches it without
     * a second entitlements stub; its CODE is asserted here through the constant the client
     * matches on, so a rename still has to be a deliberate edit in this repo. The DIAL route's own
     * suite covers the 409 path.
     */
    @Test
    fun `the dial refusals decode, and the subscription one names its code and status`() {
        val raw = fixture("district-dial-subscription.json")

        val envelope = strictJson.decodeFromString(ApiErrorEnvelope.serializer(), raw)

        assertEquals("subscription_inactive", envelope.code)
        // ⚠️ PRESENT AND FALSE, like the enrichment and membership refusals and unlike the
        // degraded body where the key is absent entirely. Three shapes, one type.
        assertEquals(false, envelope.success)
        assertTrue("must carry a message worth showing", !envelope.error.isNullOrBlank())
        assertTrue(envelope.degradedRegions.isEmpty())

        // ⛔ THE CLIENT'S CONSTANT AND THE SERVER'S STRING MUST AGREE, and this is the only place
        // that checks it. `CODE_SUBSCRIPTION_INACTIVE` is what `DialRepository` matches on; a
        // rename on either side without the other produces a refusal the app shows as generic.
        assertEquals(CODE_SUBSCRIPTION_INACTIVE, envelope.code)
        // ⚠️ The two dial codes must never collide, for the reason the two membership codes must
        // not: they mean opposite things about the account.
        assertTrue(CODE_SUBSCRIPTION_INACTIVE != CODE_OVERAGE_CAP_REACHED)

        // ⛔ `status` IS MODELLED AND MUST NOT BE BRANCHED ON. It is here because the strict decode
        // above THREW on it the first time this fixture was pinned — the gate noticing a key the
        // DTO did not know about, which is exactly what it exists for. Which Stripe states count
        // as delinquent is the server's decision and could change; the branch is the code.
        assertEquals("past_due", envelope.status)
    }

    /**
     * ⛔ THE DNC REFUSAL, PINNED PRECISELY BECAUSE IT CARRIES NOTHING TO BRANCH ON. It is a 403 with
     * a bare `{success:false, error}` and NO `code` — structurally identical to the ROLE refusal
     * the same route emits a few lines earlier, which means no client can tell them apart without
     * matching English. That is a real limitation rather than a client bug, and this test is where
     * it is recorded: if the server ever grows a `code` here, this assertion fails and the client
     * gains a branch it can take honestly.
     *
     * ⚠️ THE SENTENCE IS THEREFORE THE PRODUCT, so it is asserted. `ApiResult.Forbidden` carries
     * only a message, and the app shows it verbatim; a reworded message is the whole of what the
     * operator learns about why the call did not happen.
     */
    @Test
    fun `the DNC refusal carries a usable sentence and, deliberately, no code`() {
        val raw = fixture("district-dial-dnc.json")

        val envelope = strictJson.decodeFromString(ApiErrorEnvelope.serializer(), raw)

        assertEquals(false, envelope.success)
        assertNull("a DNC refusal carries no machine-readable code today", envelope.code)
        assertTrue(
            "the message must say the number opted out, or the operator learns nothing",
            envelope.error!!.contains("opted out"),
        )
    }

    @Test
    fun `a 403 carrying the DNC fixture reaches the caller as Forbidden with the sentence intact`() =
        runTest {
            // ⛔ THE HALF THAT MATTERS, OVER A REAL SOCKET. Decoding proves the fields are in the
            // file; this proves `mapFailure` routes a 403 to `Forbidden` AND keeps the body's
            // message — which is the only specific thing there is, since the envelope has no code.
            // A client that fell back to a generic sentence here would tell an operator "that did
            // not work" about a number that is on a do-not-call list.
            val server = MockWebServer()
            server.start()
            try {
                val api = HttpDialApi(
                    DistrictApiClient(
                        baseUrl = server.url("/"),
                        httpClient = OkHttpClient(),
                        tokens = signedInCoordinator(FakeRefreshApi().apply { rotating() }),
                    ),
                )
                server.enqueue(
                    MockResponse(
                        code = HTTP_FORBIDDEN,
                        headers = Headers.headersOf("Content-Type", "application/json"),
                        body = fixture("district-dial-dnc.json"),
                    ),
                )

                val result = api.dial(DialRequest(workspaceId = "ws-1", to = "+14165550142"))

                val forbidden = result as ApiResult.Forbidden
                assertTrue(forbidden.message.contains("opted out"))
            } finally {
                server.close()
            }
        }

    @Test
    fun `a 402 carrying the subscription fixture reaches the caller as HttpFailure with the code`() =
        runTest {
            // ⛔ 402 IS NOT ONE OF `mapFailure`'S NAMED STATUSES, so it has to fall all the way
            // through to `HttpFailure` for the code to survive at all — the same property the
            // membership 409 test above pins. A client that reached a bare
            // `HttpFailure(code = null)` here would show the server's sentence and lose the branch
            // that names the remedy.
            val server = MockWebServer()
            server.start()
            try {
                val api = HttpDialApi(
                    DistrictApiClient(
                        baseUrl = server.url("/"),
                        httpClient = OkHttpClient(),
                        tokens = signedInCoordinator(FakeRefreshApi().apply { rotating() }),
                    ),
                )
                server.enqueue(
                    MockResponse(
                        code = HTTP_PAYMENT_REQUIRED,
                        headers = Headers.headersOf("Content-Type", "application/json"),
                        body = fixture("district-dial-subscription.json"),
                    ),
                )

                val result = api.dial(DialRequest(workspaceId = "ws-1", to = "+14165550142"))

                val failure = result as ApiResult.HttpFailure
                assertEquals(HTTP_PAYMENT_REQUIRED, failure.status)
                assertEquals(CODE_SUBSCRIPTION_INACTIVE, failure.code)
                assertTrue(failure.message.isNotBlank())
            } finally {
                server.close()
            }
        }

    @Test
    fun `the client maps that exact fixture to RegionsDegraded`() {
        // ⛔ THE HALF THAT ACTUALLY MATTERS. Decoding the envelope proves the fields are there;
        // this proves the MAPPING still reaches the case that keeps "we could not look" from
        // being drawn as "there is nothing". A rename of the code would leave the test above
        // passing and this one failing.
        val raw = fixture("district-workspace-list-degraded.json")
        val envelope = DistrictApiClient.DEFAULT_JSON
            .decodeFromString(ApiErrorEnvelope.serializer(), raw)

        assertEquals(ApiErrorEnvelope.CODE_REGIONS_DEGRADED, envelope.code)
    }

    private companion object {
        /** ⚠️ Named rather than inlined: detekt's `MagicNumber` counts a bare 409 as one. */
        const val HTTP_CONFLICT = 409
        const val HTTP_FORBIDDEN = 403
        const val HTTP_PAYMENT_REQUIRED = 402
    }
}
