package com.distronode.districtai.core.auth

import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Asserts this module's PKCE derivation against vectors produced by the SERVER's own
 * TypeScript implementation.
 *
 * ⛔ WHY NOT JUST TEST THE KOTLIN AGAINST ITSELF. A self-consistency test (derive, then derive
 * again, compare) passes happily while both the challenge and the expectation are wrong in the
 * same way. The failure that actually happens in production is DISAGREEMENT BETWEEN THE TWO
 * LANGUAGES, and the server reports it as a single opaque `invalid_grant` that is
 * indistinguishable from a replayed or expired code. There is no log line, anywhere, that
 * would say "your challenge encoding is wrong" — so this test is the only place that can catch
 * it.
 *
 * ⚠️ Vectors are regenerated by the server's contract test suite, never by hand.
 */
class PkceVectorTest {

    private val vectors: List<Pair<String, String>> by lazy {
        val dir = System.getProperty("district.contracts.dir")
        assertTrue(
            "district.contracts.dir is unset; configured in core/core-auth/build.gradle.kts. " +
                "Without it this test would verify nothing and still pass.",
            !dir.isNullOrBlank(),
        )
        val file = File(dir!!, "district-pkce-vectors.json")
        assertTrue("missing PKCE vector fixture ${file.absolutePath}", file.isFile)

        Json.parseToJsonElement(file.readText()).jsonArray.map { element ->
            val obj = element.jsonObject
            obj.getValue("verifier").jsonPrimitive.content to
                obj.getValue("challenge").jsonPrimitive.content
        }
    }

    @Test
    fun `vector fixture is not empty`() {
        // An empty fixture would make every assertion below vacuous, and a .gitignore rule
        // that caught JSON files would silently leave it out of a fresh clone.
        assertTrue("PKCE vector fixture contains no vectors", vectors.isNotEmpty())
        println("PKCE vectors verified: ${vectors.size}")
    }

    @Test
    fun `kotlin derivation matches the server for every vector`() {
        vectors.forEach { (verifier, expected) ->
            assertEquals(
                "PKCE challenge mismatch for a ${verifier.length}-char verifier. The client and " +
                    "server disagree, which means EVERY login fails with an opaque invalid_grant. " +
                    "Check: digest of the ASCII STRING (not decoded bytes), base64URL (not " +
                    "standard base64), and NO padding.",
                expected,
                Pkce.deriveChallenge(verifier),
            )
        }
    }

    @Test
    fun `includes the RFC 7636 appendix B reference vector`() {
        // Independent confirmation that the SERVER is right too, not merely that the two sides
        // agree with each other. If both implementations drifted together, this is what would
        // notice.
        val rfcVerifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
        val rfcChallenge = "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"

        assertTrue(
            "the RFC 7636 reference verifier should be among the generated vectors",
            vectors.any { it.first == rfcVerifier },
        )
        assertEquals(rfcChallenge, Pkce.deriveChallenge(rfcVerifier))
    }

    @Test
    fun `generated challenges satisfy the server's shape check`() {
        // The server's isValidCodeChallenge is ^[A-Za-z0-9\-_]{43}$ and rejects anything else
        // at authorize time. Padding left on the base64 would produce 44 characters and fail
        // there — before any code is even issued.
        val shape = Regex("^[A-Za-z0-9\\-_]{43}$")
        repeat(50) {
            val generated = Pkce.newChallenge()
            assertTrue(
                "challenge '${generated.challenge}' does not match the server's accepted shape",
                shape.matches(generated.challenge),
            )
            assertTrue(
                "verifier length ${generated.verifier.length} is outside RFC 7636's 43..128",
                generated.verifier.length in 43..128,
            )
            assertTrue(
                "verifier must use only the unreserved alphabet",
                Regex("^[A-Za-z0-9\\-._~]+$").matches(generated.verifier),
            )
        }
    }

    @Test
    fun `each attempt gets fresh secrets`() {
        // A reused verifier or state across attempts would defeat both PKCE and the CSRF
        // binding. Cheap to assert, catastrophic to get wrong.
        val attempts = List(100) { Pkce.newChallenge() }
        assertEquals(100, attempts.map { it.verifier }.toSet().size)
        assertEquals(100, attempts.map { it.state }.toSet().size)
    }
}
